### Variables
@rooturl = http://localhost:7071
@fakeprincipal = eyAidXNlcklkIjogInRlc3QtdXNlciIsICJ1c2VyRGV0YWlscyI6ICJUZXN0IFVzZXIiLCAiaWRlbnRpdHlQcm92aWRlciI6ICJUZXN0IiwgInVzZXJSb2xlcyI6IFsiYWRtaW4iXSB9

### Get Events

GET {{rooturl}}/api/events/list

### Options Events

OPTIONS {{rooturl}}/api/events/list

### Get Tracks

@trackSearchTerm = david guetta

GET {{rooturl}}/api/tracks/search?query={{trackSearchTerm}}

### Options Tracks

OPTIONS {{rooturl}}/api/tracks/search?query={{trackSearchTerm}}

### Delete Cache
DELETE {{rooturl}}/api/events/deletecache
x-ms-client-principal: {{fakeprincipal}}

###